### ISSUE TITLE
DLL Issue

### ISSUE THREAD

**Issue by snkdonkey** [FortniteModding/Ultimanite#1]
how do i inject the dll? i get an error every time.

**Comment by ghost** [comment]
igcs injector

**Comment by snkdonkey** [comment]
> igcs injector

Tried that but i keep getting a Debug Error

**Comment by Ender-0001** [comment]
build as release

**Comment by siz7y** [comment]
> > igcs injector
> 
> Tried that but i keep getting a Debug Error

Build as release and it should work.
